### ISSUE TITLE
I try to reproduce your code,but it seems that your file named utils.py lacks a function called "wrap"

### ISSUE THREAD

**Issue by dglyyds** [bruceyo/GLA-GCN#1]

**Comment by bruceyo** [comment]
Thank you for the interest.
Need time to upload the whole code. This code repository is for an earlier submission. Please keep tuned.

**Comment by bruceyo** [comment]
> _No description provided._
Hi there, thank you for the interest. This code is for an earlier version.
Need time to upload the latest code together with the fine-tune module. Please keep tuned.

**Comment by dglyyds** [comment]
> 

OK,thanks

**Comment by skuley** [comment]
Hi!
I found wrap function in this repo and it works just fine!
https://github.com/vvirgooo2/MPM/blob/c0c58a572735057d6fbb1a06e4606c41bcd17b3e/common/camera.py#L23

**Comment by rniczh** [comment]
Hi, @skuley 

I have encountered the following error message when using it, have you experienced the same issue?
```
python3 run_s-agcn.py -tta --evaluate 96_gt_243_supervised.bin
Namespace(dataset='h36m', keypoints='gt', subjects_train='S1,S5,S6,S7,S8', subjects_test='S9,S11', actions='*', checkpoint='checkpoint/ h36m', checkpoint_frequency=10, resume='', evaluate='96_gt_243_supervised.bin', render=False, by_subject=False, export_training_curves= True, stride=1, epochs=80, batch_size=512, dropout=0.1, learning_rate=0.01, lr_decay=0.95, data_augmentation=False, test_time_augmentation =True, architecture='3,3,3,3,3,3', causal=False, channels=96, subset=1, downsample=1, no_eval=False, dense=False, disable_optimizations= False, linear_projection=False, bone_length_term=True, no_proj=False, debug=False, viz_subject=None, viz_action=None, viz_camera=0, viz_ video=None, viz_skip=0, viz_output=None, viz_bitrate=3000, viz_no_ground_truth=False, viz_limit=-1, viz_downsample=1, viz_size=5)
Loading dataset...
Preparing data...
Loading 2D detections...
INFO: Receptive field: 243 frames
INFO: Trainable parameter count: 1348852
Loading checkpoint checkpoint/h36m/96_gt_243_supervised.bin
Traceback (most recent call last).
  File "/Users/rnic/Workspace/GLA-GCN/run_s-agcn.py", line 245, in <module>
    model_pos_train.load_state_dict(checkpoint['model_pos'])
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for S_AGCN.
	Missing key(s) in state_dict: "data_bn.weight", "data_bn.bias", "data_bn.running_mean", "data_bn.running_var", "expand_gcn.gcn1.PA", " expand_gcn.gcn1.conv_a.0.weight", "expand_gcn.gcn1.conv_a.0.bias", "expand_gcn.gcn1.conv_a.1.weight", "expand_gcn.gcn1.conv_a.1.bias" , "expand_gcn.gcn1.conv_a.2.weight", "expand_gcn.gcn1.conv_a.2.bias", "expand_gcn.gcn1.conv_b.0.weight", "expand_gcn.gcn1.conv_b.0. bias", "expand_gcn.gcn1.conv_b.1.weight", "expand_gcn.gcn1.conv_b.1.bias", "expand_gcn.gcn1.conv_b.2.weight", "expand_gcn.gcn1.conv_b. b.2.bias", "expand_gcn.gcn1.conv_d.0.weight", "expand_gcn.gcn1.conv_d.0.bias", "expand_gcn.gcn1.conv_d.1.weight", "expand_gcn.gcn1. conv_d.1.bias", "expand_gcn.gcn1.conv_d.2.weight", "expand_gcn.gcn1.conv_d.2.bias", "expand_gcn.gcn1.down.0.weight", "expand_gcn.gcn1. down.0.bias", "expand_gcn.gcn1.down.1.weight", "expand_gcn.gcn1.down.1.bias", "expand_gcn.gcn1.down.1.running_mean", "expand_gcn.gcn1. down.1.running_var", ...
```

**Comment by faajabbari** [comment]
> Hi, @skuley
> 
> I have encountered the following error message when using it, have you experienced the same issue?
> 
> ```
> python3 run_s-agcn.py -tta --evaluate 96_gt_243_supervised.bin
> Namespace(dataset='h36m', keypoints='gt', subjects_train='S1,S5,S6,S7,S8', subjects_test='S9,S11', actions='*', checkpoint='checkpoint/ h36m', checkpoint_frequency=10, resume='', evaluate='96_gt_243_supervised.bin', render=False, by_subject=False, export_training_curves= True, stride=1, epochs=80, batch_size=512, dropout=0.1, learning_rate=0.01, lr_decay=0.95, data_augmentation=False, test_time_augmentation =True, architecture='3,3,3,3,3,3', causal=False, channels=96, subset=1, downsample=1, no_eval=False, dense=False, disable_optimizations= False, linear_projection=False, bone_length_term=True, no_proj=False, debug=False, viz_subject=None, viz_action=None, viz_camera=0, viz_ video=None, viz_skip=0, viz_output=None, viz_bitrate=3000, viz_no_ground_truth=False, viz_limit=-1, viz_downsample=1, viz_size=5)
> Loading dataset...
> Preparing data...
> Loading 2D detections...
> INFO: Receptive field: 243 frames
> INFO: Trainable parameter count: 1348852
> Loading checkpoint checkpoint/h36m/96_gt_243_supervised.bin
> Traceback (most recent call last).
>   File "/Users/rnic/Workspace/GLA-GCN/run_s-agcn.py", line 245, in <module>
>     model_pos_train.load_state_dict(checkpoint['model_pos'])
>   File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for S_AGCN.
> 	Missing key(s) in state_dict: "data_bn.weight", "data_bn.bias", "data_bn.running_mean", "data_bn.running_var", "expand_gcn.gcn1.PA", " expand_gcn.gcn1.conv_a.0.weight", "expand_gcn.gcn1.conv_a.0.bias", "expand_gcn.gcn1.conv_a.1.weight", "expand_gcn.gcn1.conv_a.1.bias" , "expand_gcn.gcn1.conv_a.2.weight", "expand_gcn.gcn1.conv_a.2.bias", "expand_gcn.gcn1.conv_b.0.weight", "expand_gcn.gcn1.conv_b.0. bias", "expand_gcn.gcn1.conv_b.1.weight", "expand_gcn.gcn1.conv_b.1.bias", "expand_gcn.gcn1.conv_b.2.weight", "expand_gcn.gcn1.conv_b. b.2.bias", "expand_gcn.gcn1.conv_d.0.weight", "expand_gcn.gcn1.conv_d.0.bias", "expand_gcn.gcn1.conv_d.1.weight", "expand_gcn.gcn1. conv_d.1.bias", "expand_gcn.gcn1.conv_d.2.weight", "expand_gcn.gcn1.conv_d.2.bias", "expand_gcn.gcn1.down.0.weight", "expand_gcn.gcn1. down.0.bias", "expand_gcn.gcn1.down.1.weight", "expand_gcn.gcn1.down.1.bias", "expand_gcn.gcn1.down.1.running_mean", "expand_gcn.gcn1. down.1.running_var", ...
> ```

I have the same problem.

**Comment by sung-sidewalk** [comment]
@rniczh @faajabbari 
this is just saying that model weights are missing such keywords. In other words, there are no weights to those keyword layers.

I think i trained on scratch.

Ill update if I did other way, its been a while I've looked into this repo :(

**Comment by WY1433223** [comment]
> Hi! I found wrap function in this repo and it works just fine! https://github.com/vvirgooo2/MPM/blob/c0c58a572735057d6fbb1a06e4606c41bcd17b3e/common/camera.py#L23

This link has expired. Could you please provide a new one? Thank you!

**Comment by LuisEstebanAcevedoBringas** [comment]
Using this `wrap` function, I was able to replicate the results without any problems. I hope this is helpful:

```python
def wrap(func, *args, unsqueeze=False):
    args = list(args)
    for i, arg in enumerate(args):
        if type(arg) == np.ndarray:
            args[i] = torch.from_numpy(arg)
            if unsqueeze:
                args[i] = args[i].unsqueeze(0)

    result = func(*args)

    if isinstance(result, tuple):
        result = list(result)
        for i, res in enumerate(result):
            if type(res) == torch.Tensor:
                if unsqueeze:
                    res = res.squeeze(0)
                result[i] = res.numpy()
        return tuple(result)
    elif type(result) == torch.Tensor:
        if unsqueeze:
            result = result.squeeze(0)
        return result.numpy()
    else:
        return result
